@startuml "TrafficControl"

class TrafficLight{
- bool lightState
void SwitchOn()
void SwitchOff()
}

class TrafficPole{   
    - TrafficLight Red
    - TrafficLight Yellow
    - TrafficLight Green
    void Stop()
    void Go()
    void SlowDown()
}

class TrafficJunction{
    
    - int noOfPole
    TrafficJunction(int noOfPole) :mnoOfPole(noOfPole)
    {
        InitalizeTrafficPoles()
    }
    InitalizeTrafficPoles()
    {
        
        for()
        {
        std::unique_ptr<traffic pole> ptr_traffic_pole;
        vec.push_back(std::move(ptr_traffic_pole));

        }
    }
    void AllowTraffic(int poleNo)
    {
        if(poleno<0 && )
        {
            for()
            {
                if (index not equal to (selected poleno -1)
                {
                    vct_trafficpole[itr]->stop(); //turning off all pole
                }
            }
            vct_trafficpole[poleNo-1]->start();
        }
    }
    void DisableTraffic(int poleNo)
    void EnableSlowDown()
    
    private:
    vector< trafficpoles*> vct_trafficpole;


   
}

Void handle_traffic_control()
{
   
   if(mode = Auto)
   {
       // start thread mThread_handle_automde 
   startautomode() 
   {
       // start timer(,Automodetimer)
      
   }
   }
   else{
       //stop timer

       
   }
   //read condition variable
   //wait untill thread stops

}

class TrafficControl{
    - TrafficJunction obj_TrafficJunction
    TrafficControl()
    {
        initilizetrafficcontrol();
    }
    initilizetrafficcontrol{
        std::thread (handle_traffic_control);
        std::thread ( userinput)
    }

    enum Mode{
       Invalid,
       Auto,
       Manual,
       Night 
    }
    void TrafficHandler()
    void AllowTraffic(int poleNo)
    void SetMode(enum Mode) ***
       void Automodetimer()
       {
        int getcurrentpoleActive();
       }    

    private:
    std::thread mThread_handle_automde;
    std::thread mThread_userinput;
}
class MessageQueue{
    MessageQueue(){
        create msgqueue
    }

}
class userinputmessagequeue{
    void sendmsg()
    void recvmsg()
}
class userinput{
    void Start()
}

userinput "1" --* "1" userinputmessagequeue
userinputmessagequeue "1" --* "1" TrafficJunction
TrafficJunction "1" --* "1" TrafficPole
TrafficPole "1" --* "1" TrafficLight

@enduml


